language: php

php:
  - 5.5
  - 5.4
  - hhvm-nightly

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'

install: composer install --dev

script: ./vendor/bin/phpunit

matrix:
  include:
    - php: hhvm
      env: PHP_EXT="memcached"
  allow_failures:
    - php: hhvm
